replicaCount: 2

image:
  repository: ghcr.io/vamor/vamolt-api
  # Keep generic here; Argo CD Application will set the exact sha
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
  name: ghcr-pull

serviceAccount:
  create: false
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  # Expose 80 inside the cluster; maps to container 8080 via targetPort: http
  port: 80

container:
  # Container listens on 8080
  port: 8080
  # Use your actuator endpoints (adjust if different)
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}

env: []
# Example:
# env:
#   - name: ASPNETCORE_ENVIRONMENT
#     value: "Production"
#   - name: CONNECTION_STRING
#     valueFrom:
#       secretKeyRef:
#         name: vamolt-api
#         key: connectionString