name: build-and-publish

on:
  push:
    branches: [ main ]
    paths:
      - 'services/demo-service/**'
      - '.github/workflows/build-and-publish.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/vamor/vamolt-api
  IMAGE_TAG: sha-${{ github.sha }}  # of: sha-${{ github.sha.substr(0,7) }} als je korte sha wil

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.IMAGE_TAG }}
      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./services/demo-service/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-gitops:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone GitOps repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/vamor/VaMolt-gitops.git
          echo "IMAGE_TAG=${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Bump dev values to new sha
        run: |
          cd VaMolt-gitops
          sed -i -E 's#(^[[:space:]]*tag:[[:space:]]*).*#\1"'${IMAGE_TAG}'"#' values/dev/vamolt-api-values.yaml

      - name: Open PR to VaMolt-gitops
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT }}
          path: VaMolt-gitops
          commit-message: "chore(dev): bump vamolt-api to ${IMAGE_TAG}"
          branch: chore/update-dev-${{ github.sha }}
          title: "chore(dev): bump vamolt-api to ${IMAGE_TAG}"
          body: "Automated PR from VaMolt build `${{ github.sha }}`"
          base: main
          labels: |
            env:dev
            automerge

      - name: Enable auto-merge (dev only)
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: vamor/VaMolt-gitops
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash