name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Voorbeeld test-job (optioneel, als je Fase 2 al hebt)
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Voeg hier je build/test stappen toe die in Fase 2 groen zijn
      - run: echo "Tests OK (placeholder)"

  build-and-push:
    # Als je tests als gating wil, laat 'needs' staan; anders verwijderen.
    needs: [tests]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # nodig om naar GHCR te pushen
    strategy:
      fail-fast: false
      matrix:
        service: [api, ingestion, web]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve org (lowercase, required by GHCR)
        id: org
        run: |
          OWNER="${GITHUB_REPOSITORY_OWNER}"
          echo "org=${OWNER,,}" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata (tags & labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.org.outputs.org }}/vamolt-${{ matrix.service }}
          tags: |
            # :latest enkel op main
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            # :<git-sha> (short)
            type=sha,format=short

      - name: Build and (conditionally) push
        uses: docker/build-push-action@v6
        with:
          context: ./services/${{ matrix.service }}
          file: ./services/${{ matrix.service }}/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }} # PRs bouwen maar pushen niet
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image digest
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "Pushed ${{ steps.meta.outputs.tags }}"